[pytest]

addopts = 
    -v
    --alluredir=reports/allure-results

testpaths = tests

python_files = test_*.py
python_functions = test_*

markers =
    smoke: quick critical tests
    skip_ci: skip test execution in CI pipeline