name: Ecommerce Web Automation

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

  schedule:
    #simulate run smoke tests everyday
    - cron: "30 11 * * *"

jobs:

  web-ui-test:

    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.14"

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Selenium Tests
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "Running Smoke Test..."
            pytest -m "smoke" --alluredir=reports/allure-results
          else
            echo "Running Test..."
            pytest -m "not skip_ci" --alluredir=reports/allure-results
          fi
                  
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4

        with:
          name: allure-results
          path: reports/allure-results